name: ClimaxGames
version: 1.0
main: net.climaxmc.ClimaxGames
authors: [computerwizjared, Jonhan_, GamerBah]
description: (c) 2015 computerwizjared. All Rights Reserved. Permission given to ClimaxMC for use of this plugin.